### ISSUE TITLE
Edit project concept

### ISSUE THREAD

**Issue by ic22b039** [ic22b039/EMBSYS_F73#5]

**Comment by ic22b039** [comment]
Made the changed according to the suggestions of the lector

**Comment by ic22b039** [comment]
[Project_Concept.pdf](https://github.com/ic22b039/EMBSYS_F73/files/15297428/Project_Concept.pdf)

**Comment by ZinkAlex** [comment]
reviewed and ready to start p(b)rogramming

**Comment by ic22b039** [comment]
[Project_Concept_Final.pdf](https://github.com/ic22b039/EMBSYS_F73/files/15297688/Project_Concept_Final.pdf)
